name: Create PR
on:
  schedule:
    - cron: '20 4 * * 3'
  workflow_dispatch:

jobs:
  update-formulae:
    runs-on: macos-latest
    steps:
      - name: Update formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.BREW_TOKEN }}
          tap: ${{ github.repository }}
          formula: task-maker-rust, neo
          livecheck: true
          message: |
            **⚠️ Do not merge this PR directly! ⚠️**
            Wait for `brew test-bot` to complete, then label it with `pr-pull` instead to make the bot build and upload the bottle.

  update-casks:
    runs-on: macos-latest
    env:
      CASKS: zephyr-sdk
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BREW_TOKEN }}
      TAP: bortoz/bortoz
    steps:
      - name: Tap repository
        run: brew tap "${{ env.TAP }}"

      - name: Update casks
        run: >
          brew livecheck --full-name --newer-only --json --quiet --tap="${{ env.TAP }}" --casks ${{ env.CASKS }} |
          yq 'map(.version.latest + " " + .cask).[]' |
          xargs -L 1 brew bump-cask-pr --no-audit --no-browse --version
