name: brew bump-formula
on:
  schedule:
    - cron: '20 4 * * 3'
  workflow_dispatch:

jobs:
  update-formulae:
    runs-on: macos-latest
    steps:
      - name: Update formulae
        uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          token: ${{ secrets.BREW_TOKEN }}
          tap: ${{ github.repository }}
          formula: task-maker-rust, neo
          livecheck: true
          message: |
            **⚠️ Do not merge this PR directly! ⚠️**
            Wait for `brew test-bot` to complete, then label it with `pr-pull` instead to make the bot build and upload the bottle.

